name: Conditions Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Build Successful"

      - name: Deploy
        if: success() && github.ref_name == 'main'
        run: echo "Deploying to Production"

      - name: Upload Logs
        if: always()
        run: echo "Uploading Logs"