name: Reusable Workflow

on:
  workflow_call:
    inputs:
      app_name:
        description: "Application Name"
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Print Application Name
        run: echo "Deploying ${{ inputs.app_name }}"