name: Outputs Demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      build_number: ${{ steps.generate.outputs.build_number }}

    steps:
      - name: Generate Build Number
        id: generate
        run: echo "build_number=1001" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploying Build ${{ needs.build.outputs.build_number }}"